### ISSUE TITLE
2d[TASK]求解模范家长需求的最小全局认识

### ISSUE THREAD

**Issue by tanchangde** [tanchangde/KingGuardian#1]
- `2d` 表示本任务的交付时间为自 Issue 打开后 2 天内
- `TASK` 表示本 Issue 为一个任务，请重点关注**任务安排、交付说明**

## 目录

- [说明](#说明)
- [任务安排](#任务安排)
- [交付说明](#交付说明)
- [已读反馈](#已读反馈)
- [ChangeLog](#changelog)

## 说明

传统教育有诸多问题，一时无法改变，直接脱离又有诸多不妥。

父母在家庭教育中，能些什么帮助孩子科学高效的学习，健康成长？

【现成信息】有哪些足够惊艳的清单、指南？

【学术学科】学术领域有哪些惊人的学习反常识？老痛点有什么新答案？又有那些新痛点卷入了足够多的人？如记忆的生存优势效应、必要难度理论

【从业人士】教育从业人士眼中，时间源头高智的家长教养需求是怎样的，活在历史中的低智家长教育需求又是怎样？

【切身感受】我们自身与循证导向的教养方式有多远的差距，如何批量解决孩子的学习焦虑？如何从底层更新孩子的学习习惯系统？

【商业产品】商业公司的产品与服务，国内外符合认知科学的优秀公司做到了什么程度？解决了什么样的需求，解决到了什么程度

## 任务安排

- 请每位队友上述上述说明中 **1** 个方向，
- 综合应用课程所学对模范家长养育孩子的过程中的需求形成最小全局认识
- 基于你获得的最小全局认识，提炼 1-3 个 BP 主题

## 交付说明

- **阅读后** 勾选文末[已读反馈](#已读反馈)
- **求解前** 查看本 Issue 队友的已认领的求解方向，尽量做到每个方向都有人认领
- **求解前** 在本 Issue 提交 Comment 回复自己将要求解的方向
- **求解后** 参照以下模版求在自己之前提交的求解方向 Comment 内增补、交付求解报告：

```markdown
# 报告标题

## 0. 主要思路
## 1. 步骤
## 2. 结论
## 3. 讨论
## 4. 参考文献

## ChangeLog
```

## 已读反馈

- [X] 长德
- [x] 润泉
- [x] 王峰
- [x] 游英
- [x] 雅琳
- [x] 九爷
- [ ] 浩涛
- [x] 淑娟

## 参考资料

- [阳老师举例结说明结业项目方向选择：产业调研 > 科普](https://github.com/AIHackers/IA002/issues/116#issuecomment-433863382)，发现信息源头更重要，而非简单科普，科普谁都可以做

## ChangeLog

- 20181028 长德 @tanchangde 初建
- 20181029 长德 @tanchangde 重构为求解模范家长需求的最小全局认识
- 20181029 长德 @tanchangde 阳老师举例说明产业调研 > 科普
- 20181029 长德 @tanchangde 根据老阳举例调整 Issue 任务方向描述

**Comment by youying0356** [comment]
游英认领【切身感受】
