### ISSUE TITLE
2d[TASK] 组块二：为什么？

### ISSUE THREAD

**Issue by tanchangde** [tanchangde/KingGuardian#6]
- `2d` 表示本任务的交付时间为自 Issue 打开后 2 天内
- `TASK` 表示本 Issue 为一个任务，请重点关注**任务安排、交付说明**

## 目录

- [说明](#说明)
- [任务清单](#任务清单)
- [交付说明](#交付说明)
- [已读反馈](#已读反馈)
- [ChangeLog](#changelog)

## 任务清单

～此处填充你所负责输出结果清单，如：

- [ ] 下载知网中小学生手游相关文献
- [ ] 识别关键变量
- [ ] 通过公开报道、报告，形成中小学生玩手游时空认识。如在线时间、空间。

...

## 交付说明

- 以 Comment 形式在本 Issue 提交结论卡片
- 一个 Comment 讲清楚一个信息点
- 卡片稍作调整便可直接嵌入项目最终路演文稿

## 参考资料

- 感受 [项目路演最终呈现 Keynote 「安身与立命——职业生涯自救指南」](https://github.com/linhaotao/AIhackers001BP-NationalstaffsCareerRPT/issues/5)
- 感受 [项目路演最呈现 演讲逐字稿 「安身与立命——职业生涯自救指南」](https://github.com/linhaotao/AIhackers001BP-NationalstaffsCareerRPT/issues/5)

## ChangeLog

- 20181104 长德 @tanchangde init

**Comment by youying0356** [comment]
## 上瘾和记忆有关

鲁登伯格的测量上瘾和记忆之间的关联实验表明：

>老鼠出了笼子，就没了瘾，变得跟第一天来到实验室时同样健康。但只要鲁登伯格一把它放回笼子，它就会发疯似的再次按压金属棒。就算把金属棒从笼子里取掉，它也会站在金属棒原本在的地方跟前。鲁登伯格猜测，老鼠的瘾在它的长期记忆里留下了强烈的印记。”



#### 参考文献

亚当·奥尔特（Adam Alter）. 《欲罢不能：刷屏时代如何摆脱行为上瘾》。

**Comment by Freshniu** [comment]
## 如何利用冷系统达成延迟满足？

鼓励孩子基于未来自我的损益来慎重考虑并进行决策，而不是基于当前的自我。

>scaffold children’s use of the “cool” system.
That is, to encourage children to mindfully consider
and make decisions based on the gains and losses of
the future self, relative to that of the current self.

参考文献：
[Sci-Hub | I want it all and i want it now: Delay of gratification in preschool children | 10.1002/dev.21249](https://sci-hub.tw/10.1002/dev.21249#)
