### ISSUE TITLE
2d[TASK] 组块三：怎么办？

### ISSUE THREAD

**Issue by tanchangde** [tanchangde/KingGuardian#7]
- `2d` 表示本任务的交付时间为自 Issue 打开后 2 天内
- `TASK` 表示本 Issue 为一个任务，请重点关注**任务安排、交付说明**

## 目录

- [说明](#说明)
- [任务清单](#任务清单)
- [交付说明](#交付说明)
- [已读反馈](#已读反馈)
- [ChangeLog](#changelog)

## 任务清单

～此处填充你所负责输出结果清单，如：

- [ ] 下载知网中小学生手游相关文献
- [ ] 识别关键变量
- [ ] 通过公开报道、报告，形成中小学生玩手游时空认识。如在线时间、空间。

...

## 交付说明

- 以 Comment 形式在本 Issue 提交结论卡片
- 一个 Comment 讲清楚一个信息点
- 卡片稍作调整便可直接嵌入项目最终路演文稿

## 参考资料

- 感受 [项目路演最终呈现 Keynote 「安身与立命——职业生涯自救指南」](https://github.com/linhaotao/AIhackers001BP-NationalstaffsCareerRPT/issues/5)
- 感受 [项目路演最呈现 演讲逐字稿 「安身与立命——职业生涯自救指南」](https://github.com/linhaotao/AIhackers001BP-NationalstaffsCareerRPT/issues/5)

## ChangeLog

- 20181104 长德 @tanchangde init

**Comment by zhujiuye2018** [comment]
### 家长对青少年游戏使用的管控行为

管控行为是家长基于对自己孩子的游戏活动了解的基础上，对孩子游戏进行干预和控制的行为。管控行为既包括直接对游戏设备和游戏时间进行硬性限制，也包括间接地管理孩子的交际圈和零花钱等。

家长对于青少年玩网络游戏的看法与玩单机游戏相比更加负面，表现在管控行为上也有所不同。在家长看来，单机游戏的负面影响要小于网络游戏的负面影响，因而相对更不需要管控。

在管控行为上，控制网络设备、控制网络连接和孩子玩游戏时亲自在旁监督是家长针对子女玩单机游戏的主要管控行为。在网络游戏的管控方面，家长更倾向于通过限制孩子与玩游戏的小孩交往来管理子女的网络游戏使用行为。显然在家长看来，网络游戏是一种非常受到人际影响的行为。

在青少年自己家里玩网络游戏和在网吧里玩网络游戏是两种不同的典型形态。针对在自己家玩网络游戏的青少年，家长的管控行为主要是限制孩子与玩游戏的孩子交往、控制游戏设备、控制网络连接和孩子玩游戏时在旁监督；针对在网吧玩网络游戏的青少年，家长更主要的管控行为是控制孩子的零用钱。

针对处于不同学龄阶段的子女，家长有着不同的管控行为。总体而言家长对念初中的子女的游戏行为的管控是最为严格的。小学高年级是游戏接触的高发期，也就是说初中阶段属于青少年游戏接触的成长期，比较容易出现游戏沉迷的阶段。家长也意识到了这一点，因此管控行为比较严格。

同时，初中孩子的家长更倾向于通过直接管控行为譬如控制游戏设备、控制网络游戏、孩子玩游戏时在旁监督，来管理孩子的游戏行为。而小学和高中孩子的家长即使管控也倾向于通过相对间接的方式，例如限制孩子与玩游戏的小孩的交往、控制孩子的零花钱、与老师沟通孩子玩游戏的情况来管理子女的游戏行为。

### **家长对青少年游戏行为的时间管理**
绝大多数家长对青少年的游戏行为持中立态度，基本上接受游戏作为青少年生活中一种重要的娱乐方式，但同时也采用不尽相同的管控手段对子女的游戏行为进行管理。从游戏时间上进行限制是家长管理青少年游戏行为的一大重要手段。从家长允许的游戏时机来看，绝大多数家长允许孩子在假期玩游戏，超过半数的家长允许孩子在周六日玩游戏，有接近一半的家长仅允许孩子在长假期玩游戏，管理相对严格。

### **家长对游戏设备的管理**
游戏设备管控是家长管理青少年游戏行为的又一重要方面。从游戏设备的拥有情况来看，台式电脑的普及率最高，76.3%的家庭都拥有台式电脑；其次是智能手机，71.5%的家庭拥有智能手机；笔记本电脑和平板电脑的拥有比例则相对较低。
电脑是青少年最主要的游戏设备。在孩子的电脑使用上，家长倾向于从时间上进行管理，严格规定孩子的使用时间（42.0%），到时间提醒孩子关电脑（29.3%）。同时，31.8%的家长把电脑放在家里的公共空间里来防止青少年私自用电脑玩游戏。采用相对间接的管理方式例如“询问孩子用电脑做什么”和“查看电脑浏览痕迹”的家长的比例较低，分别为23.3%和9.6%。

### **家长对青少年游戏下载的管理行为**

在青少年的游戏使用中，青少年自身是下载游戏的最主要人群，家长较少进行干预。这一点不管是在电脑、平板电脑还是在手机上都是同样的。说明目前来看家长们仍然只是把玩电子游戏笼统地看作一种需要管控的行为，而没有尝试从游戏类型或者具体游戏产品上进行管理。

特别是对于青少年自有比例最高的手机，有71.2%的家长表示手机上的游戏由孩子下载，而只有12.3%的游戏由家长下载。两成左右的家长会对青少年的游戏下载进行了解和限制。在平板电脑的游戏下载上，家长的参与较多，37%的家长表示平板电脑上的游戏由大人下载。

### **参考文献**
本研究隶属于国家社科基金重点项目《网络游戏与青少年发展的影响与引导研究》，课题号为11AZD112，课题负责人为刘德寰。
刘德寰，北京大学新媒体研究院教授、博士生导师，主要研究方向为传播学研究方法、市场与媒介分析、大数据分析
家长群体对青少年网络游戏使用的认知与管理行为[1] —— 一项基于全国调查的实证报告
数据来源：
腾讯平台数据收集系统，base=5401

**Comment by Shengyuansong** [comment]
## 9.  元认知 ##

### 术语：元认知 ###
- 关于认知的认知，反映或调节认知活动任一方面的知识或认知活动，以及为完成某一具体目标或任务，依据认知对象对认知过程进行主动的监测及连续的调节。
- 例子：在对某领域进行学习时，根据自身认知能力的特点和局限，有针对性的选择学习材料，制定合适的学习计划，并在学习过程中不断记录，监测学习进度，检验学习效果，并根据反馈结果来调整后续的学习计划和难度，从而提升学习效率，实现事半功倍的效果。

### 任意卡 ###
元认知学习法的重要性与意义：元认知学习法可以帮助我们更好的理解我们大脑运作的规律，这样我们就可以反过来黑客我们的大脑。另外，元认知学习法中习得的知识是【元知识】【学习方法的方法】【对认知的认知】，这些知识层级更好，是更高阶的知识，可以迁移到相对低阶的任意具体领域的知识学习当中去。
- 元认知学习包含三方面的内涵：元认知的知识、技能与体验。
- 元认知学习法的三要素：主题学习、深度学习、行动学习。
- 主题学习：通过在知识广度范围内进行搜索，快速解决学习模式中第一个【做什么？】的问题，用【模式】说话。了解该领域的牛人和具有里程碑意义的事件。主题学习通常发生在对某一领域学习的早期阶段。主题学习有一个【最小知识】学习法。找出该领域内最小的三个知识点（学科的起源、学科的核心话语体系、二级推演体系）可以快速对某一学科有较全面的理解。主题学习的五种“模式”：【一堆书>一本书】【一手信息>二手信息】【经典大于碎片】【承载信息的人大于信息本身】
- 深度学习：深度学习解决了学习模式中【如何做？】的问题。用深度说话，坚信【偏见大于平庸】。深度学习注重知识与知识之间的联结逻辑与因果关系。深度学习通常适用于学习的中后期阶段。只有通过深度学习才能突破学习的平台期。
- 行动学习：行动学习解决我们学习模式中【期待什么？】的问题。用行动说话，在学习的任一阶段我们都应该进行并坚持行动学习！用作品说话，强调输出大于输入；用行动说话，强调实践大于围观。

### 元认知能力的培养 ###
- 基本元认知策略是:
  - 将新信息与旧知识联系起来。
  - 有意识地选择思维策略。
  - 规划、监控和评估思维过程。 (迪克斯，1985)
学习如何学习，发展一套可以用来解决问题的思维过程，是教育的一个主要目标。当生活中出现学习反应无法解决的情况时，元认知行为就会发挥作用。 当习惯性反应不成功时，就需要元认知技能。 元认知策略在认知方面的指导，在应用方面的练习，将帮助学生在一生中成功地解决问题。
- 发展元认知行为的策略
  - 识别"你知道什么"和"你不知道什么"在研究活动开始时，学生需要对自己的知识做出有意识的决定。 最初，学生们写下"我已经知道的... ..."和"我想学习的东西... ..."当学生们研究这个话题时，他们会核实、澄清和扩展，或者用更准确的信息取代他们的每一个初始陈述。
  - 谈论思考。谈论思考很重要，因为学生需要一个思考的词汇。 在计划和解决问题的情况下，教师应该大声思考，以便学生能够遵循已经证明的思维过程。 建模和讨论发展学生需要思考和讨论自己思考的词汇。 在学生使用思维过程时，标记思维过程对于学生认识思维技能也很重要。
  - 保持思考日记。记录他们对模棱两可和矛盾的认识，并评论他们是如何处理困难的。 
  - 规划和自我调节。学生必须承担越来越多的责任，规划和调节他们的学习。 当学习被他人计划和监控时，学习者很难自我导向。可以教学生制定学习活动计划，包括估计时间需求、组织材料和完成活动所需的时间安排程序。 资源中心的灵活性和获取各种资料的途径使得学生可以做到这一点。 评估标准必须与学生一起制定，以便他们在学习活动中学会自己思考和提出问题。
  - 思考过程的汇报。结束活动的重点是讨论学生的思维过程，以发展认识的战略，可以适用于其他学习情况，他们评估自己的成功，丢弃不适当的策略，确定那些对将来有用的策略，并寻找有前途的替代方法。
  - 自我评估。由于学生认识到不同学科的学习活动是相似的，他们将开始转移学习策略到新的情况。
建立元认知环境

在这个迅速变化的世界里，教学的挑战是帮助学生发展不会过时的技能。 

### 参考文献 ###

[工作谈](https://www.yangzhiping.com/worksmarter/chapter5/talk001)
通识部落卡片
[元认知能力的培养](https://www.ericdigests.org/pre-9218/developing.htm)

**Comment by youying0356** [comment]
![](https://ws1.sinaimg.cn/large/006tNbRwgy1fx9qmdtq1rj30s80hm3zj.jpg)
